name: publish

on:
  workflow_dispatch:

jobs:
  push:
    name: push package on pypi
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'    
      - name: update pip
        run: |
          python3 -m pip install --upgrade pip        
      - name: install pep517
        run: |
          pip install pep517
      - name: build
        run: python3 -m pep517.build --source --binary --out-dir dist/ .
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PASSWORD }}
      - name: executable format
        run: | 
          pip install pyinstaller
          pyinstaller --name pyvitemadose --exclude-module pyvitemadose.update --clean --onefile pyvitemadose/__init__.py
      - uses: actions/upload-artifact@v2
        with:
          name: pyvitemadose_executable_linux
          path: /home/runner/work/pyvitemadose/pyvitemadose/dist/pyvitemadose                    
      - name: tweet
        env: 
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          VERSION: ${{ steps.vars.outputs.relase_tag }}
        run: pip install twython && python .github/publish_tweet.py            

